### ISSUE TITLE
feature/Receive as argument name of yaml file

### ISSUE THREAD

**Issue by elohimtenorio** [tomi-vanek/microts#6]
Hello, I like your project vision, will be a very useful feature supporting any other name of yaml file,  like microts --name othername.yaml
what do you think?

**Comment by tomi-vanek** [comment]
Thanks for the good suggestion, I will implement it right after vacation.

**Comment by tomi-vanek** [comment]
`microts --schema othername.yaml` - `-s` or `--schma` parameter with schema file name (or absolute / relative path to it) allows file selection. Schema must be OpenAPI 2.0 (constraint from used tools - will be fixed in future version of the generator - https://github.com/tomi-vanek/microts/issues/5). Both YAML and JSON formats are supported (JSON is converted to YAML).

I updated documentation - as the usage was not clear.
